"""Update primary key in vote model

Revision ID: 046fc6071ccd
Revises: 0e3ce5459b9c
Create Date: 2023-01-25 21:03:42.881395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046fc6071ccd'
down_revision = '0e3ce5459b9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
