"""Add Full-text search for Post

Revision ID: 2af421d51153
Revises: 046fc6071ccd
Create Date: 2023-01-30 15:18:04.123130

"""
from alembic import op
import sqlalchemy as sa

from src.database.models import TSVector


# revision identifiers, used by Alembic.
revision = "2af421d51153"
down_revision = "046fc6071ccd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "__ts_vector__",
            TSVector(),
            sa.Computed(
                "to_tsvector('english', title || ' ' || content)", persisted=True
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_post__ts_vector__",
        "posts",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_post__ts_vector__", table_name="posts", postgresql_using="gin")
    op.drop_column("posts", "__ts_vector__")
    # ### end Alembic commands ###
