"""create inital tables

Revision ID: 39491838f11e
Revises: 
Create Date: 2023-01-17 15:09:51.369445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39491838f11e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
