"""Create tables

Revision ID: 3a9a980ffb53
Revises: 39491838f11e
Create Date: 2023-01-19 18:29:26.081034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9a980ffb53'
down_revision = '39491838f11e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
