"""empty message

Revision ID: 5a85bfb9822b
Revises: 3a9a980ffb53
Create Date: 2023-01-19 18:46:34.943390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a85bfb9822b'
down_revision = '3a9a980ffb53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
