"""Add cascade delete

Revision ID: 641dadd61a71
Revises: 80824b09fe99
Create Date: 2023-01-24 17:06:36.427081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641dadd61a71'
down_revision = '80824b09fe99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
