"""Add user_id in vote model

Revision ID: 9692d2b9c78c
Revises: 1040ed81a770
Create Date: 2023-01-25 20:47:25.905169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9692d2b9c78c'
down_revision = '1040ed81a770'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_votes', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'comment_votes', 'users', ['user_id'], ['id'])
    op.add_column('post_votes', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'post_votes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_votes', type_='foreignkey')
    op.drop_column('post_votes', 'user_id')
    op.drop_constraint(None, 'comment_votes', type_='foreignkey')
    op.drop_column('comment_votes', 'user_id')
    # ### end Alembic commands ###
